"""
Django settings for breathe_esg project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
import sys
from pathlib import Path
import environ

# ------------------------------------------------------------------------------
# Path Definitions
# ------------------------------------------------------------------------------
# Resolves to the 'backend' directory
BASE_DIR = Path(__file__).resolve().parent.parent

# Add 'apps' subdirectory path to sys.path to allow clean imports
sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))

# ------------------------------------------------------------------------------
# Environment Variables Load
# ------------------------------------------------------------------------------
env = environ.Env(
    DEBUG=(bool, False),
    ALLOWED_HOSTS=(list, ['127.0.0.1', 'localhost']),
)

# Look for the .env file at the project root level (parent of backend/)
ENV_FILE_PATH = os.path.join(BASE_DIR.parent, '.env')
if os.path.exists(ENV_FILE_PATH):
    environ.Env.read_env(ENV_FILE_PATH)

# ------------------------------------------------------------------------------
# Security Configurations
# ------------------------------------------------------------------------------
SECRET_KEY = env('SECRET_KEY', default='django-insecure-default-temporary-key-string-for-local-boot')
DEBUG = env('DEBUG')
ALLOWED_HOSTS = env.list('ALLOWED_HOSTS')

# ------------------------------------------------------------------------------
# Application Registry
# ------------------------------------------------------------------------------
DJANGO_CORE_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

THIRD_PARTY_APPS = [
    'rest_framework',
]

CUSTOM_DOMAIN_APPS = [
    'apps.companies.apps.CompaniesConfig',
    'apps.ingestion.apps.IngestionConfig',
    'apps.normalization.apps.NormalizationConfig',
    'apps.review.apps.ReviewConfig',
    'apps.audit.apps.AuditConfig',
]

INSTALLED_APPS = DJANGO_CORE_APPS + THIRD_PARTY_APPS + CUSTOM_DOMAIN_APPS

# ------------------------------------------------------------------------------
# Middleware Configurations
# ------------------------------------------------------------------------------
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'breathe_esg.urls'

# ------------------------------------------------------------------------------
# Template Configurations
# ------------------------------------------------------------------------------
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'breathe_esg.wsgi'

# ------------------------------------------------------------------------------
# Database Configurations (PostgreSQL)
# ------------------------------------------------------------------------------
DATABASES = {
    'default': env.db(
        'DATABASE_URL',
        default='postgres://esg_analyst:secure_password_here@localhost:5432/breathe_esg_db'
    )
}

# ------------------------------------------------------------------------------
# Password Validation Rules
# ------------------------------------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ------------------------------------------------------------------------------
# Localization & Timezone Rules
# ------------------------------------------------------------------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# ------------------------------------------------------------------------------
# Static Files Configurations
# ------------------------------------------------------------------------------
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ------------------------------------------------------------------------------
# Django REST Framework Settings
# ------------------------------------------------------------------------------
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
}
