# Generated by Django 5.0.14 on 2026-05-27 18:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('SAP_PROCUREMENT', 'SAP Fuel and Procurement'), ('UTILITY_PORTAL', 'Electricity Utility Portal'), ('TRAVEL_CONCUR', 'Corporate Travel Concur/Navan JSON')], max_length=50)),
                ('configuration_payload', models.JSONField(blank=True, default=dict, help_text='Stores client-specific column mappings, plant code translation tables, or API parameters.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='data_sources', to='companies.company')),
            ],
            options={
                'db_table': 'data_sources',
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='RawRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_id', models.UUIDField(db_index=True, help_text='Groups all rows imported during the same file transaction.')),
                ('sequence_number', models.IntegerField(help_text='The line index in the source file for precise audit tracking.')),
                ('raw_payload', models.JSONField(help_text='Contains the exact, untranslated JSON or CSV row key-values.')),
                ('processing_state', models.CharField(choices=[('UNPROCESSED', 'Unprocessed'), ('NORMALIZED', 'Successfully Normalized'), ('REJECTED', 'Rejected on Structural Validation')], db_index=True, default='UNPROCESSED', max_length=30)),
                ('structural_error', models.TextField(blank=True, help_text='Details structural compilation or column failures.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raw_records', to='companies.company')),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raw_records', to='ingestion.datasource')),
            ],
            options={
                'db_table': 'raw_records',
                'ordering': ['job_id', 'sequence_number'],
            },
        ),
        migrations.CreateModel(
            name='PlantLookup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sap_plant_code', models.CharField(db_index=True, max_length=50)),
                ('facility_name', models.CharField(max_length=255)),
                ('grid_region_code', models.CharField(help_text='Used to resolve region-specific Scope 2 grid factors.', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plant_lookups', to='companies.company')),
            ],
            options={
                'db_table': 'plant_lookups',
                'unique_together': {('company', 'sap_plant_code')},
            },
        ),
    ]
