# Generated by Django 5.0.14 on 2026-05-27 18:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('ingestion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('RECORD_INGESTED', 'Raw Ingestion Job Completed'), ('METRIC_RECALCULATED', 'Recalculation and Factor Update'), ('METRIC_APPROVED', 'Analyst Approved Metric'), ('PERIOD_LOCKED', 'Reporting Period Frozen'), ('LEDGER_VERIFIED', 'System Integrity Checked')], db_index=True, max_length=50)),
                ('payload_snapshot', models.JSONField(help_text='Stores the serialized properties of modified elements or lock contexts.')),
                ('action_timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='companies.company')),
            ],
            options={
                'db_table': 'audit_events',
                'ordering': ['-action_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='NormalizedRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('FUEL_COMBUSTION', 'Stationary Fuel Combustion (Scope 1)'), ('ELECTRICITY_CONSUMPTION', 'Electricity Consumption (Scope 2)'), ('BUSINESS_TRAVEL', 'Corporate Business Travel (Scope 3)')], db_index=True, max_length=50)),
                ('scope_classification', models.CharField(choices=[('SCOPE_1', 'Scope 1 - Direct Emissions'), ('SCOPE_2', 'Scope 2 - Indirect Grid Emissions'), ('SCOPE_3', 'Scope 3 - Value Chain Indirect')], db_index=True, max_length=30)),
                ('reporting_date', models.DateField(db_index=True)),
                ('raw_quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('raw_unit', models.CharField(max_length=50)),
                ('normalized_quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('normalized_unit', models.CharField(max_length=50)),
                ('travel_category', models.CharField(blank=True, choices=[('flight', 'Flight'), ('hotel', 'Hotel'), ('ground', 'Ground')], help_text='Category of travel activity.', max_length=20, null=True)),
                ('origin_airport_code', models.CharField(blank=True, help_text='IATA code of origin airport', max_length=10, null=True)),
                ('destination_airport_code', models.CharField(blank=True, help_text='IATA code of destination airport', max_length=10, null=True)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, help_text='Travel distance in kilometers', max_digits=12, null=True)),
                ('emission_factor_applied', models.DecimalField(decimal_places=8, max_digits=18)),
                ('co2e_metric_tons', models.DecimalField(decimal_places=6, max_digits=18)),
                ('review_status', models.CharField(choices=[('PENDING_REVIEW', 'Awaiting Analyst Action'), ('SUSPICIOUS', 'Flagged as Statistical Outlier'), ('DISPUTED', 'Opened Back to Source Verification'), ('APPROVED', 'Certified by Analyst'), ('LOCKED', 'Locked for Compliance Audit')], db_index=True, default='PENDING_REVIEW', max_length=30)),
                ('is_locked', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='normalized_records', to='companies.company')),
                ('raw_record', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='normalized', to='ingestion.rawrecord')),
            ],
            options={
                'db_table': 'normalized_records',
                'ordering': ['-reporting_date'],
            },
        ),
        migrations.CreateModel(
            name='ReviewDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('APPROVE', 'Certified and Approved'), ('DISPUTE', 'Disputed Back to Source'), ('FLAG_SUSPICIOUS', 'Flagged as Outlier / Suspicious'), ('LOCK', 'Locked for Compliance Audit')], max_length=30)),
                ('previous_state', models.CharField(max_length=30)),
                ('new_state', models.CharField(max_length=30)),
                ('notes', models.TextField(help_text='Detailed context or explanation of the certification decision or dispute.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analyst', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_decisions', to='companies.company')),
                ('normalized_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='normalization.normalizedrecord')),
            ],
            options={
                'db_table': 'review_decisions',
                'ordering': ['-created_at'],
            },
        ),
    ]
